# Generated by Django 6.0.8 on 2026-09-16 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0010_alter_deviceparametervalue_device_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRcmJobs",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        db_column="job_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_column="external_id", max_length=100),
                ),
                ("from_time", models.DateTimeField(db_column="from_time")),
                ("to_time", models.DateTimeField(db_column="to_time")),
                (
                    "reading_reason",
                    models.CharField(db_column="reading_reason", max_length=100),
                ),
                (
                    "job_created_at",
                    models.DateTimeField(auto_now_add=True, db_column="job_created_at"),
                ),
                (
                    "job_last_run_at",
                    models.DateTimeField(
                        blank=True, db_column="job_last_run_at", null=True
                    ),
                ),
                (
                    "job_run_count",
                    models.IntegerField(
                        db_column="job_run_count",
                        default=0,
                        help_text="Number of times the job has been run",
                    ),
                ),
                ("message", models.TextField(db_column="message")),
                (
                    "device_id",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_rcm_records",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "db_table": "billing_rcm_jobs",
                "ordering": ["-job_created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_run_count"],
                        name="billing_rcm_records_job_run_count_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NonSmToSmJobs",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        db_column="job_id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_created_at",
                    models.DateTimeField(auto_now_add=True, db_column="job_created_at"),
                ),
                (
                    "job_run_at",
                    models.DateTimeField(blank=True, db_column="job_run_at", null=True),
                ),
                ("payload", models.JSONField(db_column="payload")),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_column="job_status",
                        max_length=100,
                    ),
                ),
                ("job_message", models.TextField(db_column="job_message")),
                (
                    "retries",
                    models.IntegerField(
                        db_column="retries",
                        default=1,
                        help_text="Number of times the job has been retried",
                    ),
                ),
                (
                    "consumer_id",
                    models.ForeignKey(
                        db_column="consumer_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_sm_to_sm_jobs_consumer",
                        to="core.consumer",
                    ),
                ),
                (
                    "non_sm_device_id",
                    models.ForeignKey(
                        db_column="non_sm_device_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_sm_to_sm_jobs_non_smart",
                        to="core.device",
                    ),
                ),
                (
                    "service_point_id",
                    models.ForeignKey(
                        db_column="service_point_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_sm_to_sm_jobs_service_point",
                        to="core.servicepoint",
                    ),
                ),
                (
                    "sm_device_id",
                    models.ForeignKey(
                        db_column="sm_device_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_sm_to_sm_jobs_smart",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "db_table": "non_sm_to_sm_jobs",
                "ordering": ["-job_created_at"],
                "indexes": [
                    models.Index(fields=["job_id"], name="non_sm_to_sm_jobs_job_id_idx")
                ],
            },
        ),
    ]
