# Generated by Django 6.0.8 on 2026-09-16 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bses_module", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="billingrcmjobs",
            new_name="billing_rcm_jobs_run_count_idx",
            old_name="billing_rcm_records_job_run_count_idx",
        ),
    ]
