# Generated by Django 6.0.8 on 2026-09-16 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bses_module",
            "0002_rename_billing_rcm_records_job_run_count_idx_billing_rcm_jobs_run_count_idx",
        ),
        ("core", "0011_alter_devicetypetemplatemap_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BillingRcmJobs",
            new_name="BillingRcmJob",
        ),
        migrations.RenameModel(
            old_name="NonSmToSmJobs",
            new_name="NonSmToSmJob",
        ),
    ]
