# Generated by Django 6.0.8 on 2026-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0003_rename_billingrcmjobs_billingrcmjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='job_id',
            field=models.CharField(db_column='job_id', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
