# Generated by Django 6.0.8 on 2026-09-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0004_alter_nonsmtosmjob_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='consumer_id',
            field=models.CharField(db_column='consumer_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='non_sm_device_id',
            field=models.CharField(db_column='non_sm_device_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='service_point_id',
            field=models.CharField(db_column='service_point_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='sm_device_id',
            field=models.CharField(db_column='sm_device_id', max_length=100),
        ),
    ]
