# Generated by Django 6.0.8 on 2026-09-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0005_alter_nonsmtosmjob_consumer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='service_point_id',
            field=models.CharField(db_column='service_point_id', max_length=100, null=True),
        ),
    ]
