# Generated by Django 6.0.8 on 2026-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0006_alter_nonsmtosmjob_service_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='non_sm_device_id',
            field=models.CharField(db_column='non_sm_device_id', max_length=100, null=True),
        ),
    ]
