# Generated by Django 6.0.8 on 2026-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0007_alter_nonsmtosmjob_non_sm_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsmtosmjob',
            name='job_run_at',
            field=models.DateTimeField(auto_now=True, db_column='job_run_at'),
        ),
    ]
