# Generated by Django 6.0.8 on 2026-09-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0008_alter_nonsmtosmjob_job_run_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrcmjob',
            name='job_run_count',
        ),
        migrations.AddField(
            model_name='billingrcmjob',
            name='remaining_attempts',
            field=models.PositiveIntegerField(db_column='remaining_attempts', default=1, help_text='Number of execution attempts remaining'),
        ),
    ]
