# Generated by Django 6.0.8 on 2026-09-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0009_remove_billingrcmjob_job_run_count_and_more'),
        ('core', '0015_alter_electricalnode_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingrcmjob',
            name='billing_rcm_jobs_run_count_idx',
        ),
        migrations.AddIndex(
            model_name='billingrcmjob',
            index=models.Index(fields=['remaining_attempts'], name='billing_rcm_remaining_attempts_idx'),
        ),
    ]
