# Generated by Django 6.0.8 on 2026-09-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0010_remove_billingrcmjob_billing_rcm_jobs_run_count_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingrcmjob',
            new_name='billing_rcm_retries_idx',
            old_name='billing_rcm_remaining_attempts_idx',
        ),
    ]
