# Generated by Django 6.0.8 on 2026-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0011_rename_billing_rcm_remaining_attempts_idx_billing_rcm_retries_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrcmjob',
            name='message',
            field=models.TextField(db_column='message', null=True),
        ),
    ]
