# Generated by Django 6.0.8 on 2026-09-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bses_module', '0012_alter_billingrcmjob_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrcmjob',
            name='message',
            field=models.TextField(blank=True, db_column='message', null=True),
        ),
    ]
