# Generated by Django 6.0.8 on 2026-09-04 19:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "consumer_id",
                    models.CharField(
                        help_text="Unique Consumer ID / Account ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consumer_name", models.CharField(max_length=255)),
                ("customer_entry_date", models.DateField()),
                (
                    "sub_division_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dtr_code", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "consumers",
                "indexes": [
                    models.Index(fields=["consumer_name"], name="consumer_name_idx"),
                    models.Index(
                        fields=["sub_division_code"], name="consumer_subdiv_idx"
                    ),
                    models.Index(fields=["dtr_code"], name="consumer_dtr_idx"),
                    models.Index(
                        fields=["customer_entry_date"], name="consumer_entry_dt_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsumerParameterDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Canonical parameter key", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "STRING"),
                            ("NUMBER", "NUMBER"),
                            ("BOOLEAN", "BOOLEAN"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "consumer_parameter_definitions",
                "indexes": [
                    models.Index(fields=["is_active"], name="cp_def_active_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceParameterDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Canonical parameter key", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "STRING"),
                            ("NUMBER", "NUMBER"),
                            ("BOOLEAN", "BOOLEAN"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "device_parameter_definitions",
                "indexes": [
                    models.Index(fields=["is_active"], name="dp_def_active_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Canonical template name", max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "device_templates",
                "indexes": [
                    models.Index(fields=["name"], name="device_template_name_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Canonical device type name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_register",
                    models.CharField(
                        help_text="Canonical register name", max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "device_types",
                "indexes": [models.Index(fields=["name"], name="device_type_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique meter/device identifier",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phase", models.CharField(blank=True, max_length=20, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "current_rating",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "multiplying_factor",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=8
                    ),
                ),
                ("ct_ratio", models.CharField(blank=True, max_length=50, null=True)),
                ("pt_ratio", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InService", "InService"),
                            ("Removed", "Removed"),
                            ("InStore", "InStore"),
                        ],
                        default="InService",
                        max_length=20,
                    ),
                ),
                ("is_smart_meter", models.BooleanField(default=True)),
                (
                    "prepaid_postpaid_flag",
                    models.CharField(
                        choices=[("PREPAID", "PREPAID"), ("POSTPAID", "POSTPAID")],
                        default="POSTPAID",
                        max_length=20,
                    ),
                ),
                ("net_meter_flag", models.BooleanField(default=False)),
                ("shunt_capacitor_flag", models.BooleanField(default=False)),
                (
                    "prepaid_opening_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "register_group",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "device_template",
                    models.ForeignKey(
                        db_column="device_template",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="core.devicetemplate",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        db_column="device_type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="core.devicetype",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceTypeTemplateMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_template",
                    models.ForeignKey(
                        db_column="device_template_uuid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_types",
                        to="core.devicetemplate",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        db_column="device_type_uuid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="core.devicetype",
                    ),
                ),
            ],
            options={
                "db_table": "device_type_template_map",
            },
        ),
        migrations.CreateModel(
            name="ElectricalNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("DISCOM", "DISCOM"),
                            ("CIRCLE", "CIRCLE"),
                            ("DIVISION", "DIVISION"),
                            ("SUB_DIVISION", "SUB_DIVISION"),
                            ("FEEDER", "FEEDER"),
                            ("DTR", "DTR"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        help_text="NULL for root node",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="children",
                        to="core.electricalnode",
                    ),
                ),
            ],
            options={
                "db_table": "electrical_nodes",
            },
        ),
        migrations.CreateModel(
            name="GeographicalNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("STATE", "STATE"),
                            ("DISTRICT", "DISTRICT"),
                            ("CITY", "CITY"),
                            ("AREA", "AREA"),
                            ("LOCALITY", "LOCALITY"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        help_text="NULL for root node",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="children",
                        to="core.geographicalnode",
                    ),
                ),
            ],
            options={
                "db_table": "geographical_nodes",
            },
        ),
        migrations.CreateModel(
            name="ServicePoint",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Unique Service Point ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "electrical_node",
                    models.ForeignKey(
                        db_column="electrical_node_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="service_points",
                        to="core.electricalnode",
                    ),
                ),
                (
                    "geographical_node",
                    models.ForeignKey(
                        db_column="geographical_node_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="service_points",
                        to="core.geographicalnode",
                    ),
                ),
            ],
            options={
                "db_table": "service_points",
            },
        ),
        migrations.CreateModel(
            name="DeviceInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField()),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL while installation is active",
                        null=True,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="installations",
                        to="core.device",
                    ),
                ),
                (
                    "service_point",
                    models.ForeignKey(
                        db_column="service_point_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="device_installations",
                        to="core.servicepoint",
                    ),
                ),
            ],
            options={
                "db_table": "device_installations",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="NULL while contract is active", null=True
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        db_column="consumer_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="core.consumer",
                    ),
                ),
                (
                    "service_point",
                    models.ForeignKey(
                        db_column="service_point_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="core.servicepoint",
                    ),
                ),
            ],
            options={
                "db_table": "contracts",
            },
        ),
        migrations.CreateModel(
            name="ServicePointParameterDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Canonical parameter key", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "STRING"),
                            ("NUMBER", "NUMBER"),
                            ("BOOLEAN", "BOOLEAN"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "service_point_parameter_definitions",
                "indexes": [
                    models.Index(fields=["is_active"], name="sp_def_active_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ServicePointParameterValue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("recorded_at", models.DateTimeField()),
                (
                    "parameter",
                    models.ForeignKey(
                        db_column="parameter_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="core.servicepointparameterdefinition",
                    ),
                ),
                (
                    "service_point",
                    models.ForeignKey(
                        db_column="service_point_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_values",
                        to="core.servicepoint",
                    ),
                ),
            ],
            options={
                "db_table": "service_point_parameter_values",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsumerParameterValue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("recorded_at", models.DateTimeField()),
                (
                    "consumer",
                    models.ForeignKey(
                        db_column="consumer_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_values",
                        to="core.consumer",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        db_column="parameter_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="core.consumerparameterdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "consumer_parameter_values",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["consumer", "parameter", "-recorded_at"],
                        name="cp_val_cons_param_rec_idx",
                    ),
                    models.Index(fields=["-recorded_at"], name="cp_val_rec_desc_idx"),
                    models.Index(
                        fields=["parameter", "-recorded_at"],
                        name="cp_val_param_rec_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceParameterValue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("recorded_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_values",
                        to="core.device",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        db_column="parameter_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="core.deviceparameterdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "device_parameter_values",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "parameter", "-recorded_at"],
                        name="dp_val_dev_param_rec_idx",
                    ),
                    models.Index(fields=["-recorded_at"], name="dp_val_rec_desc_idx"),
                    models.Index(
                        fields=["parameter", "-recorded_at"],
                        name="dp_val_param_rec_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="device_status_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "is_smart_meter"], name="device_status_smart_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["manufacturer"], name="device_mfr_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["category", "phase"], name="device_cat_phase_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetypetemplatemap",
            index=models.Index(fields=["device_type"], name="dttm_device_type_idx"),
        ),
        migrations.AddIndex(
            model_name="devicetypetemplatemap",
            index=models.Index(
                fields=["device_template"], name="dttm_device_template_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="electricalnode",
            index=models.Index(fields=["node_type"], name="elec_node_type_idx"),
        ),
        migrations.AddIndex(
            model_name="electricalnode",
            index=models.Index(fields=["parent"], name="elec_node_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="electricalnode",
            index=models.Index(
                fields=["node_type", "name"], name="elec_node_type_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geographicalnode",
            index=models.Index(fields=["node_type"], name="geo_node_type_idx"),
        ),
        migrations.AddIndex(
            model_name="geographicalnode",
            index=models.Index(fields=["parent"], name="geo_node_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="geographicalnode",
            index=models.Index(
                fields=["node_type", "name"], name="geo_node_type_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepoint",
            index=models.Index(fields=["electrical_node"], name="sp_elec_node_idx"),
        ),
        migrations.AddIndex(
            model_name="servicepoint",
            index=models.Index(fields=["geographical_node"], name="sp_geo_node_idx"),
        ),
        migrations.AddIndex(
            model_name="servicepoint",
            index=models.Index(
                fields=["electrical_node", "geographical_node"], name="sp_elec_geo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceinstallation",
            index=models.Index(
                fields=["service_point", "is_active"], name="dev_inst_sp_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceinstallation",
            index=models.Index(
                fields=["device", "is_active"], name="dev_inst_dev_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceinstallation",
            index=models.Index(
                fields=["start_date", "end_date"], name="dev_inst_dates_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["service_point", "is_active"], name="contract_sp_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["consumer", "is_active"], name="contract_cons_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["start_date", "end_date"], name="contract_dates_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepointparametervalue",
            index=models.Index(
                fields=["service_point", "parameter", "-recorded_at"],
                name="sp_val_sp_param_rec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepointparametervalue",
            index=models.Index(fields=["-recorded_at"], name="sp_val_rec_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="servicepointparametervalue",
            index=models.Index(
                fields=["parameter", "-recorded_at"], name="sp_val_param_rec_idx"
            ),
        ),
    ]
