# Generated by Django 6.0.8 on 2026-09-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumerparameterdefinition",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("STRING", "STRING"),
                    ("NUMBER", "NUMBER"),
                    ("BOOLEAN", "BOOLEAN"),
                ],
                default="STRING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consumerparametervalue",
            name="parameter",
            field=models.ForeignKey(
                db_column="parameter_uuid",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="values",
                to="core.consumerparameterdefinition",
            ),
        ),
        migrations.AlterField(
            model_name="consumerparametervalue",
            name="recorded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="deviceparameterdefinition",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("STRING", "STRING"),
                    ("NUMBER", "NUMBER"),
                    ("BOOLEAN", "BOOLEAN"),
                ],
                default="STRING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deviceparametervalue",
            name="recorded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="servicepoint",
            name="electrical_node",
            field=models.ForeignKey(
                db_column="electrical_node_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_points",
                to="core.electricalnode",
            ),
        ),
        migrations.AlterField(
            model_name="servicepoint",
            name="geographical_node",
            field=models.ForeignKey(
                db_column="geographical_node_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_points",
                to="core.geographicalnode",
            ),
        ),
        migrations.AlterField(
            model_name="servicepointparameterdefinition",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("STRING", "STRING"),
                    ("NUMBER", "NUMBER"),
                    ("BOOLEAN", "BOOLEAN"),
                ],
                default="STRING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicepointparametervalue",
            name="parameter",
            field=models.ForeignKey(
                db_column="parameter_uuid",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="values",
                to="core.servicepointparameterdefinition",
            ),
        ),
        migrations.AlterField(
            model_name="servicepointparametervalue",
            name="recorded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
