# Generated by Django 6.0.8 on 2026-09-05 06:30

from django.db import migrations


def create_electrical_root_nodes(apps, schema_editor):
    ElectricalNode = apps.get_model("core", "ElectricalNode")

    ElectricalNode.objects.get_or_create(
        name="Root",
        parent=None,
    )


def create_geographical_root_nodes(apps, schema_editor):
    GeographicalNode = apps.get_model("core", "GeographicalNode")

    GeographicalNode.objects.get_or_create(
        name="Root",
        parent=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_consumerparameterdefinition_data_type_and_more"),
    ]

    operations = [
        migrations.RunPython(create_electrical_root_nodes),
        migrations.RunPython(create_geographical_root_nodes),
    ]
