# Generated by Django 6.0.8 on 2026-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_create_root_nodes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="prepaid_postpaid_flag",
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_type",
            field=models.CharField(
                choices=[("PREPAID", "PREPAID"), ("POSTPAID", "POSTPAID")],
                default="PREPAID",
                max_length=20,
            ),
        ),
    ]
