# Generated by Django 6.0.8 on 2026-09-09 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_device_prepaid_postpaid_flag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetemplate",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="devicetypetemplatemap",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
