# Generated by Django 6.0.8 on 2026-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_devicetemplate_id_alter_devicetype_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetype",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
