# Generated by Django 6.0.8 on 2026-09-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_devicetype_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="service_point",
            field=models.OneToOneField(
                db_column="service_point_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="core.servicepoint",
            ),
        ),
    ]
