# Generated by Django 6.0.8 on 2026-09-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_contract_service_point"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="devicetypetemplatemap",
            constraint=models.UniqueConstraint(
                fields=("device_type", "device_template"),
                name="unique_device_type_template",
            ),
        ),
    ]
