# Generated by Django 6.0.8 on 2026-09-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_devicetypetemplatemap_unique_device_type_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceparametervalue",
            name="device",
            field=models.ForeignKey(
                db_column="device_uuid",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parameter_values",
                to="core.device",
            ),
        ),
        migrations.AlterField(
            model_name="deviceparametervalue",
            name="parameter",
            field=models.ForeignKey(
                db_column="parameter_uuid",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="values",
                to="core.deviceparameterdefinition",
            ),
        ),
    ]
