# Generated by Django 6.0.8 on 2026-09-16 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_deviceparametervalue_device_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetypetemplatemap",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
