# Generated by Django 6.0.8 on 2026-09-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_devicetypetemplatemap_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consumer',
            name='consumer_entry_dt_idx',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='customer_entry_date',
        ),
    ]
