# Generated by Django 6.0.8 on 2026-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_consumer_consumer_entry_dt_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalnode',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
