# Generated by Django 6.0.8 on 2026-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_geographicalnode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalnode',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
