# Generated by Django 6.0.8 on 2026-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_geographicalnode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalnode',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='geographicalnode',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
