# Generated by Django 6.0.8 on 2026-09-24 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_electricalnode_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInstallationParameterDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Canonical parameter key', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(choices=[('STRING', 'STRING'), ('NUMBER', 'NUMBER'), ('BOOLEAN', 'BOOLEAN')], default='STRING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'device_installation_parameter_definitions',
                'indexes': [models.Index(fields=['is_active'], name='dip_def_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceInstallationParameterValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_value', models.CharField(blank=True, max_length=255, null=True)),
                ('end_value', models.CharField(blank=True, max_length=255, null=True)),
                ('device_installation', models.ForeignKey(db_column='device_installation_id', on_delete=django.db.models.deletion.PROTECT, related_name='parameter_values', to='core.deviceinstallation')),
                ('parameter', models.ForeignKey(db_column='parameter_uuid', on_delete=django.db.models.deletion.PROTECT, related_name='values', to='core.deviceinstallationparameterdefinition')),
            ],
            options={
                'db_table': 'device_installation_parameter_values',
                'constraints': [models.UniqueConstraint(fields=('device_installation', 'parameter'), name='dip_val_unique_inst_param')],
            },
        ),
    ]
